<?php

function landing_init(){
	register_post_type('landing', array(
		'label' => __('Landings', 'dem'),
		'labels' => array(
			'name' => __('Landings', 'dem'),
			'singular_name' => __('Landing', 'dem'),
			'menu_name' => __('Landings', 'dem'),
			'name_admin_bar' => __('Landing', 'dem'),
			'add_new' => __('Add new', 'dem'),
			'add_new_item' => __('Add new landing', 'dem'),
			'new_item' => __('New landing', 'dem'),
			'edit_item' => __('Edit landing', 'dem'),
			'view_item' => __('View landing', 'dem'),
			'view_items' => __('View landings', 'dem'),
			'all_items' => __('All landings', 'dem'),
			'search_items' => __('Search landings', 'dem'),
			'parent_item_colon' => __('Parent landing:', 'dem'),
			'not_found' => __('No landings found.', 'dem'),
			'not_found_in_trash' => __('No landings found in Trash.', 'dem'),
			'archives' => __('Landings archives', 'dem'),
			'attributes' => __('Landings attributes', 'dem'),
			'insert_into_item' => __('Insert into landing', 'dem'),
			'uploaded_to_this_item' => __('Uploaded to this landing', 'dem'),
			'featured_image' => __('Featured image', 'dem'),
			'set_featured_image' => __('Set featured image', 'dem'),
			'remove_featured_image' => __('Remove featured image', 'dem'),
			'use_featured_image' => __('Use as featured image', 'dem'),
			'filter_items_list' => __('Filter landings list', 'dem'),
			'items_list_navigation' => __('Landings list navigation', 'dem'),
			'items_list' => __('Landings list', 'dem'),
			'item_published' => __('Landing published.', 'dem'),
			'item_published_privately' => __('Landing published privately.', 'dem'),
			'item_reverted_to_draft' => __('Landing reverted to draft.', 'dem'),
			'item_scheduled' => __('Landing scheduled.', 'dem'),
			'item_updated' => __('Landing updated.', 'dem'),
		),
		'description' => __('Landing.', 'dem'),
		'public' => true,
		'exclude_from_search' => false,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_nav_menus' => true,
		'show_in_menu' => true,
		'show_in_admin_bar' => true,
		'query_var' => true,
		'rewrite' => array('slug' => 'landings'),
		'capability_type' => 'page',
		'has_archive' => true,
		'hierarchical' => false,
		'menu_position' => 4,
		'menu_icon' => 'dashicons-layout',
		'supports' => array('title', 'editor', 'revisions'),
		'delete_with_user' => false,
		'map_meta_cap' => null,
		'show_in_rest' => true,
		'rest_base' => 'landings'
	));
}
add_action('init', 'landing_init');